export const SIDEBAR_BACKGROUND = 'SIDEBAR_BACKGROUND';
export const SIDEBAR_FILTER = 'SIDEBAR_FILTER';
export const SIDEBAR_BACKGROUND_IMAGE = 'SIDEBAR_BACKGROUND_IMAGE';
export const NEW_CAMPAIGN_ADDITION = 'NEW_CAMPAIGN_ADDITION';
export const UPDATE_CAMPAIGN_DETAILS = 'UPDATE_CAMPAIGN_DETAILS'